### ISSUE TITLE
Inconsistent behaviour between Windows 7 and Linux.

### ISSUE THREAD

**Issue by daxpedda** [BurntSushi/termcolor#12]
I tested this on Windows 7 with both cmd and psh, same behaviour.

---
1. ```rust
   let mut stdout = StandardStream::stdout(ColorChoice::Always);
   stdout.set_color(ColorSpec::new().set_fg(Some(Color::Green))).unwrap();
   ```
   Linux: After the program is done, new text color reverts to it's default color.
   Windows 7: Ends up changing the color of any text in the terminal until the end of the terminals lifetime.
2. ```rust
   let mut stdout = StandardStream::stdout(ColorChoice::Always);
   stdout.set_color(ColorSpec::new().set_fg(Some(Color::Blue))).unwrap();
   writeln!(&mut stdout, "stdout: blue text!").unwrap();

   // creating the buffer before or after the change of color doesn't change the outcome
   let bufwtr = BufferWriter::stdout(ColorChoice::Always);
   let mut buffer = bufwtr.buffer();
   buffer.set_color(ColorSpec::new().set_fg(Some(Color::Green))).unwrap();
   writeln!(&mut buffer, "buffer: green text!").unwrap();
   // resetting the color with `set_color(&ColorSpec::new())`
   buffer.set_color(&ColorSpec::new()).unwrap();
   bufwtr.print(&buffer).unwrap();

   writeln!(&mut stdout, "stdout: text after `set_color(&ColorSpec::new())`!").unwrap();
   ```
   Linux: First line is blue. Second line is green. Third line is back to it's default color.
   Windows 7: First line is blue. Second and third lines are green.
3. ```rust
   let mut stdout = StandardStream::stdout(ColorChoice::Always);
   stdout.set_color(ColorSpec::new().set_fg(Some(Color::Blue))).unwrap();
   writeln!(&mut stdout, "stdout: blue text!").unwrap();

   // buffer created after color was changed
   let bufwtr = BufferWriter::stdout(ColorChoice::Always);
   let mut buffer = bufwtr.buffer();
   buffer.set_color(ColorSpec::new().set_fg(Some(Color::Green))).unwrap();
   writeln!(&mut buffer, "buffer: green text!").unwrap();
   // resetting the color with `reset()`
   buffer.reset().unwrap();
   bufwtr.print(&buffer).unwrap();

   writeln!(&mut stdout, "stdout: text after `reset()`!").unwrap();
   ```
   Linux: First line is blue. Second line is green. Third line is back to it's default color.
   Windows 7: First line is blue. Second line is green. Third line is green.
4. ```rust
   let mut stdout = StandardStream::stdout(ColorChoice::Always);
   // buffer created before color was changed
   let bufwtr = BufferWriter::stdout(ColorChoice::Always);
   let mut buffer = bufwtr.buffer();

   stdout.set_color(ColorSpec::new().set_fg(Some(Color::Blue))).unwrap();
   writeln!(&mut stdout, "stdout: blue text!").unwrap();

   buffer.set_color(ColorSpec::new().set_fg(Some(Color::Green))).unwrap();
   writeln!(&mut buffer, "buffer: green text!").unwrap();
   // resetting the color with `reset()`
   buffer.reset().unwrap();
   bufwtr.print(&buffer).unwrap();

   writeln!(&mut stdout, "stdout: text after `reset()`!").unwrap();
   ```
   Linux & Windows 7: First line is blue. Second line is green. Third line is back to it's default color.

---
I'm not sure if any of this is intended or not.

**Comment by BurntSushi** [comment]
Hi! Thanks for filing an issue. I can believe that some of those programs lead to inconsistent results. However, this is not necessarily a "Linux vs Windows" thing. For example, in your first program, I can produce different results on Linux between different shells (zsh and bash). In general, if you aren't properly reseting your colors and are mixing buffered writing and non-buffered writing, then you're going to have a bad time. `termcolor` really isn't in the business of preventing you from screwing it up.

In future, **please provide complete programs instead of code snippets.**

**Comment by daxpedda** [comment]
Thanks for the fast response.
> In future, **please provide complete programs instead of code snippets.**

These were complete programs. Just wrap a `fn main` around it. I will clarify that in the future, my bad!

In any case, the bug that I see here is that resetting colors in buffers yields to different results across shells. If termcolor isn't in the business to eliminate inconsistencies there, fine by me, it should be documented somewhere though imho.
