### ISSUE TITLE
Windows: piping to less drops the color except for the first line.

### ISSUE THREAD

**Issue by mookid** [BurntSushi/termcolor#16]
Hi and thanks for the awesome library! I meet the following issue, I am not sure it is a bug in termcolor, a misuse of the library, a limitation of windows console API or something else.

---------------------------------------------------------------------

When piping stdout to `less -R`, I expect the colors to be unchanged. 

It appears that the first line keeps its color, the formatting info is reset starting from the second one.

This is on windows 10 v19.03, cmd.exe. 

### Test program:
```
use termcolor::{
    Color::Red,
    ColorChoice, ColorSpec, StandardStream, WriteColor,
};
use std::io::Write;

fn main() {
    test(ColorChoice::Auto).unwrap();
    test(ColorChoice::AlwaysAnsi).unwrap();
    test(ColorChoice::Always).unwrap();
}

fn test(cc: ColorChoice) -> std::io::Result<()> {
    println!("------------------------- {:?}", cc);
    let stdout = StandardStream::stdout(cc);
    let mut stdout = stdout.lock();

    stdout.set_color(ColorSpec::default().set_fg(Some(Red)))?;
    stdout.write_all(b"foo\n")?;
    stdout.write_all(b"bar\n")?;
    stdout.set_color(&ColorSpec::default())?;
    Ok(())
}
```

### output:

![image](https://user-images.githubusercontent.com/7757342/59568710-cd878300-907e-11e9-8a13-15684fb8473c.png)

Note that the output bytes are the following:
```
C:\Users\Nathan\src\scratch_rust\test_termcolor$ cargo run | less -F
    Finished dev [unoptimized + debuginfo] target(s) in 0.03s
     Running `target\debug\test_termcolor.exe`
------------------------- Auto
ESC[0mESC[31mfoo
bar
ESC[0m------------------------- AlwaysAnsi
ESC[0mESC[31mfoo
bar
ESC[0m------------------------- Always
ESC[0mESC[31mfoo
bar
ESC[0m
```

**Comment by BurntSushi** [comment]
This appears to be the fault of `less`, and has nothing to do with `termcolor`. The actual raw output is correct, as demonstrated by printing to a terminal directly.

I wasn't able to find any official documentation, but this [SO question](https://stackoverflow.com/questions/32925593/prevent-less-r-from-resetting-colours-across-newlines) should help clarify things. Also, `man less` makes it clear that the `-r` and `-R` flags are "best effort."

You should be setting colors and what not on a per line basis.

**Comment by mookid** [comment]
Thanks for the help!
