### ISSUE TITLE
support virtual terminal sequences on Windows 10

### ISSUE THREAD

**Issue by galich** [BurntSushi/termcolor#2]
[SetConsoleMode()](https://docs.microsoft.com/en-us/windows/console/setconsolemode) with `ENABLE_VIRTUAL_TERMINAL_PROCESSING` flag should allow use of regular VTS and eliminate need to call to `SetConsoleTextAttribute()`.

It does work on Windows 10.
It doesn't work on Windows 7 where SetConsoleMode() fails and GetLastError() returns ERROR_INVALID_PARAMETER (87).

More details here https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences

**Comment by BurntSushi** [comment]
Could you please explain what specific action item you're hoping will happen as a result of this issue? In particular, how does termcolor's existing support for VTS fall short of what you're requesting here?

**Comment by galich** [comment]
I guess I'm confused with `wincolor::win::Console::set()` fn here https://github.com/BurntSushi/termcolor/blob/master/wincolor/src/win.rs#L77-L78

It looks like call to `SetConsoleTextAttribute()` happens all the time, no matter if console supports VTS or not?

**Comment by BurntSushi** [comment]
wincolor is a low level library for interacting with the console. It isn't wincolor's job to transparently enable VT for you. It just gives you the tools to do it. Like, I don't understand why this is was opened when there is specifically a method [to do exactly what you're suggesting](https://docs.rs/wincolor/1.0.0/x86_64-pc-windows-msvc/wincolor/struct.Console.html#method.set_virtual_terminal_processing).

termcolor, being the higher level cross platform library, handles this transparently for you.

It sounds like what you want is already done so I'm just going to close this.

**Comment by galich** [comment]
Got it, thanks for the explanation!


________________________________
