### ISSUE TITLE
RGB colors not working on OSX

### ISSUE THREAD

**Issue by mookid** [BurntSushi/termcolor#21]
Hi,

The following program fails to display colors:

```

use std::io::{self, Write, Result};
use termcolor::{Color, Color::Rgb, ColorChoice, ColorSpec, StandardStream, WriteColor};

fn main() -> Result<()> {
    let input = "xxxx";
    format(input, None, Some(Rgb(0x33, 0x55, 0x33)), true)?;
    format(input, Some(Rgb(0x33, 0x99, 0x33)), None, false)?;
    format(input, None, Some(Rgb(0x55, 0x33, 0x33)), true)?;
    format(input, Some(Rgb(0x99, 0x33, 0x33)), None, false)?;
    Ok(())
}

fn format(input: &str, fg: Option<Color>, bg: Option<Color>, bold: bool) -> Result<()> {    
    let mut stdout = StandardStream::stdout(ColorChoice::Always);
    stdout.set_color(ColorSpec::new().set_fg(fg).set_bg(bg).set_bold(bold))?;
    write!(&mut stdout, "{}",  input)?;
    stdout.reset()?;
    write!(&mut stdout, "\n")?;
    Ok(())
}

```

which outputs something like this:
![image](https://user-images.githubusercontent.com/7757342/64391131-e3865d80-d047-11e9-866e-70e5c3a449d3.png)

This is on OSX 10.12.1, and has been reported on 10.14.6 as well (https://github.com/mookid/diffr/issues/16#issuecomment-527694501_);
rustc is 1.39.0-nightly (c6e9c76c5 2019-09-04).

I got it working previously with another version of the rust toolchain (and probably the same version of OSX but I can't be sure).

Note that Color::Green, Red... seem to work.

**Comment by BurntSushi** [comment]
This sounds like an issue with your terminal. It seems to be working for me.

**Comment by mookid** [comment]
I can reproduce on both iterm2 and the terminal app.

Let me know if any additional information can help.

**Comment by upsuper** [comment]
I don't know about iTerm2, but it seems that this doesn't work because macOS terminal doesn't support true color. (It does support 256 colors, though) If I run it inside alacritty, it works.

I'm not sure whether there is anything can be done in termcolor. Maybe it can provide an addition layer to translate true color to its closest color in the 256 palette on supported term, but that can probably be in a separate crate.

**Comment by BurntSushi** [comment]
Yeah, that's what I figured. Not all terminals support all colors. This is expected and normal.

**Comment by mookid** [comment]
@BurntSushi thanks for the info.
