### ISSUE TITLE
Feature request: dyn WriteColor -> io::Write

### ISSUE THREAD

**Issue by CAD97** [BurntSushi/termcolor#22]
This is possible in user-land, and I'm doing it currently, you just make a wrapper that forwards all the methods:

```rust
struct EraseColor<'a>(&'a mut dyn WriteColor);
struct EraseColor<'a>(&'a mut dyn WriteColor);
impl io::Write for EraseColor<'_> {
    fn write(&mut self, buf: &[u8]) -> io::Result<usize> {
        self.0.write(buf)
    }
    fn write_vectored(&mut self, bufs: &[io::IoSlice<'_>]) -> io::Result<usize> {
        self.0.write_vectored(bufs)
    }
    fn flush(&mut self) -> io::Result<()> {
        self.0.flush()
    }
    fn write_all(&mut self, buf: &[u8]) -> io::Result<()> {
        self.0.write_all(buf)
    }
    fn write_fmt(&mut self, fmt: fmt::Arguments<'_>) -> io::Result<()> {
        self.0.write_fmt(fmt)
    }
    fn by_ref(&mut self) -> &mut Self
    where
        Self: Sized,
    {
        self
    }
}
```

I'm not sure the best way for the library to do this, but this seems like something that would be useful to have in the library, and can encourage use of `&mut dyn WriteColor` (avoiding monomorphization cost) as it's more obvious how to interact with code that uses `io::Write`. `NoColor` already offers the `io::Write -> WriteColor` direction.

**Comment by BurntSushi** [comment]
@CAD97 Thanks for the issue!

I'm having a bit of difficultly understanding what problems this solves. In particular, it looks like `Box<dyn WriteColor>` and `&mut dyn WriteColor` already work? For example:

```
use std::io::Write;

use termcolor::{Color, ColorChoice, ColorSpec, StandardStream, WriteColor};

fn main() {
    let mut stdout = StandardStream::stdout(ColorChoice::Always);
    stdout.set_color(ColorSpec::new().set_fg(Some(Color::Green))).unwrap();

    let mut wtr: &mut dyn WriteColor = &mut stdout;
    writeln!(&mut wtr, "green text").unwrap();
}
```

I guess I'm trying to understand why you're proposing a wrapper type?

**Comment by CAD97** [comment]
It's specifically to pass `&mut dyn WriteColor` to a function written against `io::Write`.

But apparently I missed the fact that it... actually works? I'll come back if I find the code where this was an issue :sweat_smile:
