### ISSUE TITLE
Don't print colors when TERM=xterm-mono

### ISSUE THREAD

**Issue by aleksator** [BurntSushi/termcolor#27]
[There's an issue](https://github.com/rust-lang/cargo/issues/7646) with a downstream package that uses this library (cargo), where users requested that it shouldn't print colors when XTERM=xterm-mono.

I'll submit a PR that adds a check for this value in a moment.

**Comment by BurntSushi** [comment]
Is there some source you can link to where this is actually a standard way of disabling colors? I've never seen this being used in other CLI programs. For example:

![grep-colors](https://user-images.githubusercontent.com/456674/75611648-66194280-5aea-11ea-9341-464d32f6349b.png)

I'm quite hesitant to just start loading up a bunch of checks like this us they are widely supported.

**Comment by BurntSushi** [comment]
cc @ainar-g who originally reported this to Cargo.

**Comment by aleksator** [comment]
I actually couldn't find anything official for that myself, apart from https://invisible-island.net/xterm/terminfo-contents.html#tic-xterm-mono mentioning that it is "monochrome", which I suppose you can read as "does not support colors".

Since I never attempted to turn off colors myself, I trust users of such features to have a better knowledge on the topic. Hence the submitted PR.

I should probably have worded this as a question indeed.
Thank you for looking into it.

**Comment by ainar-g** [comment]
<p>
@BurntSushi  On many systems, <code>grep</code> is an alias for
<code>grep --color=auto</code>.  It definitely is on stock Ubuntu.  It
doesn't show the colours when you exclude the alias or use
<code>/bin/grep</code>.  You can also try e.g.
<code>env TERM=xterm-mono vim ./sh.tmp.sh</code>.
</p>

**Comment by aleksator** [comment]
I found that using TERM=dumb may impact applications in ways other than color handling, e.g. ncurses applications refuse to work.
source: https://stackoverflow.com/questions/39001517/features-obligatory-for-term-dumb-terminal

@BurntSushi The last word is yours ;)

**Comment by BurntSushi** [comment]
I'm going to pass on this for now. I think adding more exceptions to "env does not support colors" needs a more holistic treatment. If someone wanted to open a new issue and kick off that discussion, I'd be happy about that. See also #41.

>  On many systems, `grep` is an alias for `grep --color=auto`. It definitely is on stock Ubuntu. It doesn't show the colours when you exclude the alias or use `/bin/grep`

Right. That was intentional. The behavior of what to do in "auto" mode is exactly the question here. :-)
