### ISSUE TITLE
Strip escape codes when not attached to terminal

### ISSUE THREAD

**Issue by wtetzner** [BurntSushi/termcolor#3]
I was wondering if a new ColorChoice option could be added, or maybe Auto could be updated, to have support for stripping the escape codes if output is not attached to a terminal, like [Jansi](https://github.com/fusesource/jansi).

It looks like Auto already does something similar, but in particular, it would be nice if the colors could be stripped out when piping the output to another program.

Is this something that would be difficult to implement?

**Comment by BurntSushi** [comment]
Huh? Sorry, but I don't understand your request. If you don't want colors, then use the [`NoColor`](https://docs.rs/termcolor/1.0.1/termcolor/struct.NoColor.html) adapter. If you want to operate at the level of `ColorChoice`, then use [`ColorChoice::Never`](https://docs.rs/termcolor/1.0.1/termcolor/enum.ColorChoice.html#variant.Never).

If you're talking about literally interpreting ANSI escape codes and then stripping them before sending them to the underlying writer, then I don't understand what your use case is, and it doesn't really seem like something that belongs in this crate.

If you simply want to enable/disable colors based on whether the output is attached to a terminal or not, then you should use the [`atty`](https://crates.io/crates/atty) crate.

**Comment by wtetzner** [comment]
Yes, I just want to enable/disable colors based on whether the output is attached to a terminal or not.

It looks like this does the trick:

    let mut stdout = StandardStream::stdout(if atty::is(Stream::Stdout) { ColorChoice::Auto } else { ColorChoice::Never });

Thanks for your help!
