### ISSUE TITLE
Incorrect line-wrapping when used in PROMPT/PS1 on zsh

### ISSUE THREAD

**Issue by spease** [BurntSushi/termcolor#32]
zsh linewrapping does not work correctly when using termcolor to generate prompts. I suspect this is due to zsh considering the escape sequences as being characters that take up printable space for the purpose of determining when the end of the line has been reached. It looks like the solution may be to use `%{` and `}%` to wrap escape sequences.

This occurs with my lengthy "[omniprompt](https://github.com/spease/omniprompt)" if you configure .zshrc to use it with
```
PROMPT='$(omniprompt $?)'`
PS2=" %B%%F{blue}>%b%f "
RPROMPT=""
```

A couple informative links:
https://stackoverflow.com/questions/31166479/zsh-prompt-substitution-issues
https://stackoverflow.com/questions/30470306/how-can-i-prevent-ansi-escape-sequences-in-my-python-script-from-messing-with-my

This does not happen with ion.

**Comment by BurntSushi** [comment]
I'm not sure I really see this as a problem that termcolor should solve. Random shell specific hacks for niche circumstances don't really seem like a good fit for termcolor. If you are wanting to implement something as specialized as a prompt for a specific shell, then I'd probably just drop the dependency on termcolor and write the escape sequences you want directly.

**Comment by BurntSushi** [comment]
I am going to close this since I don't think anything has changed since my previous comment and thus I don't see any immediate action items.
