### ISSUE TITLE
impl WriteColor for std::io::Sink

### ISSUE THREAD

**Issue by segeljakt** [BurntSushi/termcolor#37]
Hi,

Would it be possible to extend termcolor so that it can be used with [`std::io::Sink`](https://doc.rust-lang.org/std/io/fn.sink.html). A `Sink` emits no output and can be useful in cases where you want to measure the execution time without I/O included.

Thank you for the great crate

**Comment by BurntSushi** [comment]
Seems reasonable. A PR is welcome.

**Comment by BurntSushi** [comment]
Closed by #38

**Comment by coolreader18** [comment]
Would you be able to cut a release with this? I find myself needing it as well.

**Comment by BurntSushi** [comment]
Done in `termcolor 1.1.3`.
