### ISSUE TITLE
Add missing colors

### ISSUE THREAD

**Issue by bestouff** [BurntSushi/termcolor#44]
The `Color` enum only has 8 named colors, whereas every terminal I know has:
- 16 user-settable colors, which by default are the 8 first colors defined in `Color` followed by the same ones, brighter
- 240 fixed colors
- a direct 24-bits color mode

Would it be possible to add the missing 8 named colors to `Color`, i.e. `Grey`, `LightBlue`, `LightGreen`, ..., `BrightWhite` ?
For now, if I want to specify e.g. "light yellow" I have to use `Color::Ansi256(11)`. This is neither easily discoverable nor readable.

**Comment by BurntSushi** [comment]
The colors come from here: https://en.wikipedia.org/wiki/ANSI_escape_code#3-bit_and_4-bit

I'm not inclined to add a bunch of colors. I think the existing options are sufficient. Improving the docs with links to pages of how to choose colors using, e.g., `Ansi256`, sounds like a good idea though.

> whereas every terminal I know has

Legacy Windows consoles don't. The docs even _explicitly_ call this out: The Ansi256 and Rgb color types are not supported when writing colors on Windows using the console. If they are used on Windows, then they are silently ignored and no colors will be emitted.

> For now, if I want to specify e.g. "light yellow" I have to use `Color::Ansi256(11)`.

You can also use `Rgb`.

**Comment by bestouff** [comment]
> >  For now, if I want to specify e.g. "light yellow" I have to use Color::Ansi256(11).
> 
> You can also use Rgb.

No I can't. `Rgb` will output a fixed color, whereas I want to output the "light yellow" which has been choosen by the terminal theme. Only the first 16 ANSI colors respect the terminal theme.  

How about aliasing colors 8..15 to colors 0..7 in the Windows console case ?

**Comment by BurntSushi** [comment]
> No I can't. `Rgb` will output a fixed color, whereas I want to output the "light yellow" which has been choosen by the terminal theme. Only the first 16 ANSI colors respect the terminal theme.

Are there any docs you can link about this?

What's the difference between these other 8 "light" colors and the "intense" or "bright" versions of them? Those are supported by setting the `intense` option: https://docs.rs/termcolor/1.1.2/termcolor/struct.ColorSpec.html#method.intense

**Comment by bestouff** [comment]
There's no difference, the "intense" version are effectively the "light" ones. However they are only accessible through an API to build a `ColorSpec` whereas I can put a `Color` directly into a struct. For example in my code:
```rust
pub trait NameKind {
    const COLOR: Color;
}

impl<'a> NameKind for Subckt<'a> {
    const COLOR: Color = Color::Yellow;
}

impl<'a> NameKind for Instance<'a> {
    const COLOR: Color = Color::Green;
}
```

Now I would have to add a `bool` just to access these 8 colors, I "feel" this is wrong because they are just some other colors, not some special attribute like bold or italic.

**Comment by BurntSushi** [comment]
If there's no difference, then I would prefer to keep the current API.

**Comment by bestouff** [comment]
But your API doesn't work in all cases.
For example I can't select bright yellow foreground with normal blue background, either both the background *and* foreground are bright or not. To individually select brightness I have to manually use `Ansi256(x)` where `x` isn't documented, and isn't even the same as the `Color`'s order.

Failing testcase:
```rust
use std::io::{self, Write};
use termcolor::{Color, Color::*, ColorChoice, ColorSpec, StandardStream, WriteColor};

fn main() {
    let mut stdout = StandardStream::stdout(ColorChoice::Always);
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Color::Yellow))
                .set_bg(Some(Color::Blue)),
        )
        .unwrap();
    writeln!(&mut stdout, "works");
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Color::Yellow))
                .set_bg(Some(Color::Blue))
                .set_intense(true),
        )
        .unwrap();
    writeln!(&mut stdout, "works");
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Color::Yellow))
                .set_intense(true)
                .set_bg(Some(Color::Blue)),
        )
        .unwrap();
    writeln!(&mut stdout, "doesn't work");
    stdout
        .set_color(
            ColorSpec::new()
                .set_bg(Some(Color::Blue))
                .set_intense(true)
                .set_fg(Some(Color::Yellow)),
        )
        .unwrap();
    writeln!(&mut stdout, "doesn't work");
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Ansi256(3)))
                .set_bg(Some(Ansi256(4))),
        )
        .unwrap();
    writeln!(&mut stdout, "works");
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Ansi256(11)))
                .set_bg(Some(Ansi256(4))),
        )
        .unwrap();
    writeln!(&mut stdout, "works");
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Ansi256(3)))
                .set_bg(Some(Ansi256(12))),
        )
        .unwrap();
    writeln!(&mut stdout, "works");
    stdout
        .set_color(
            ColorSpec::new()
                .set_fg(Some(Ansi256(11)))
                .set_bg(Some(Ansi256(4))),
        )
        .unwrap();
    writeln!(&mut stdout, "works");
}
```
