### ISSUE TITLE
Feature Request: Merge `Buffer`s

### ISSUE THREAD

**Issue by ThePuzzlemaker** [BurntSushi/termcolor#45]
It would be helpful if it were possible to merge two `Buffer`s. I'm assuming this function would probably only work if the two buffers were of the same type (i.e. `BufferInner::Ansi`, `BufferInner::NoColor`, `BufferInner::Windows`) and had the same `ColorChoice`.

**Comment by BurntSushi** [comment]
Can you give more details? By merge, do you mean _concatenate_?

Can you elaborate on the use case for this? Why do you want to do it?

**Comment by ThePuzzlemaker** [comment]
I can't say I remember why I needed this, but I don't really anymore.
