### ISSUE TITLE
`ColorSpec` should provide methods for strikethrough text

### ISSUE THREAD

**Issue by k12ish** [BurntSushi/termcolor#46]
Both [colored](https://docs.rs/colored/2.0.0/colored/trait.Colorize.html#tymethod.strikethrough) and [ansi_term](http://www.willusher.io/ispc-rs/ansi_term/enum.Colour.html#method.strikethrough) provide methods for creating strikethrough text.

I would appreciate it if `termcolor` could maintain feature parity with these crates.

**Comment by BurntSushi** [comment]
A PR is welcome.

**Comment by tgross35** [comment]
Hey @BurntSushi would PR #47 be more or less what is needed if it were rebased?

If so, I can update it (I'm not sure why k12ish deleted the branch)

**Comment by k12ish** [comment]
Apologies, I forgot that I'd even made changes to my fork of `termcolor`, so I deleted the repository 

I am happy to hand over this issue to @tgross35, if they are interested

**Comment by tgross35** [comment]
Ok, I took your changes and opened #67. Pretty straightforward, should just need a review

**Comment by tgross35** [comment]
Woohoo, thank you!
