### ISSUE TITLE
[Question] - Only color a word

### ISSUE THREAD

**Issue by margual56** [BurntSushi/termcolor#52]
How would you go about coloring a single word in an output?
For example, in python (from [this question](https://stackoverflow.com/questions/57251653/highlight-specific-words-in-a-sentence-in-python) in stackoverflow):
```
from termcolor import colored
text='left foot right foot left foot right. Feet in the day, feet at night.'
l1=['foot','feet']
formattedText = []
for t in text.lower().split():
    if t in l1:
        formattedText.append(colored(t,'white','on_red'))
    else: 
        formattedText.append(t)

print(" ".join(formattedText))
```

I wasn't able to find any documentation, example or question about this... is it not possible in the Rust version?

Of course this wouldn't only apply to printing a single word in color, but for example printing two sentences to the stdout and only color one of them.

**Comment by BurntSushi** [comment]
I think this a better question for a general Rust help forum. The [docs for termcolor show how to set colors](https://rust-lang.github.io/rfcs/1068-rust-governance.html#moderation-team), so you just need to combine that with code that splits a string into words.
