### ISSUE TITLE
Serde support?

### ISSUE THREAD

**Issue by virtualritz** [BurntSushi/termcolor#57]
Would you take a PR that adds serialization support (behind a `serde` feature flag) to `Color` and `ColorChoice`?

These types are candidates to be stored in a config file for a typical cli app and adding this would save people (like myself) from requiring to make a wrapper type to derive those. :)

**Comment by BurntSushi** [comment]
I'd prefer not. I think it's more appropriate for the application to specify how these things should be serialized/deserialized instead of coupling yourself to some decision I (or we) make about its format in this library.

**Comment by virtualritz** [comment]
Not sure I understand. I mean if a user wants their own (de-)serialization implementation they just add `termcolor` without the `serde` feature and do so. But if they don't, having `serde` support is just a feature flag away.

I went ahead since it was a quick one ( #58). Up to you. :).

**Comment by virtualritz** [comment]
I.e. what I mean is: `serde` `derive` [doesn't lock you into any specific format](https://serde.rs/derive.html).
It just means `Color` and `ColorChoice` can be (de-)serialized to *any* format someone has made a crate for that is `serde` compatible. E.g. JSON, RON, YAML, etc.

Also see [official Rust API guidelines](https://rust-lang.github.io/api-guidelines/interoperability.html#data-structures-implement-serdes-serialize-deserialize-c-serde) on this topic.

**Comment by BurntSushi** [comment]
For example, someone might want to encode `Rgb` as `#RRGGBB` in a string within a larger format (like a JSON string or a TOML string). But if they just use the serde impls in your PR, you'll get something very different than that string.

I'm aware of the API guidelines. I'm on the libs-api team.

**Comment by virtualritz** [comment]
I that case wouldn't you just pull in `termcolor` w/o the `serde` flag?
And then implement those traits on your wrapper type? The latter you need anyway because of the orphan rules. I.e. you can either have those implemented as part of `termcolor` or you need to wrap the resp. `termcolor` types anyway. 

I.e. I totally agree with you as far as your example goes but I don't see how my PR would prevent you to do whatever impl you need on your wrapper type.

And that is true even if the unwrapped type in `termcolor` implemented those traits – or am I missing something?

**Comment by BurntSushi** [comment]
It's not about prevention. It's about adding something that is probably not right that is frictionless to use. Sometimes friction is a feature. And I think that applies here. I want people to think about their format.
