### ISSUE TITLE
Colors don't reset when interleaving writes to stdout/stderr

### ISSUE THREAD

**Issue by romanows** [BurntSushi/termcolor#6]
I wanted to use termcolor v1.0.3 to color my program's stdout and stderr in different colors.  This [minimal code](https://play.rust-lang.org/?gist=a00a45f4c9f6d69a4ebbdeb52e5a3bc6&version=nightly&mode=debug&edition=2015) runs but doesn't color my content in the way I would expect.  Do you think this use-case should be addressed by termcolor or do you think it's worth adding a comment to the documentation to warn off other newbies?  I'm very new to Rust and terminal coloring, so apologies if this is misguided.

The code in the above link is reproduced here:
```rust
extern crate termcolor;

use std::io::Write;
use termcolor::{Color, ColorChoice, ColorSpec, StandardStream, WriteColor};

fn main() {
    let mut stderr = StandardStream::stderr(ColorChoice::Always);
    stderr.set_color(ColorSpec::new().set_fg(Some(Color::Red))).unwrap();
    
    let mut stdout = StandardStream::stdout(ColorChoice::Always);
    stdout.set_color(ColorSpec::new().set_fg(Some(Color::Green))).unwrap();
    
    writeln!(&mut stderr, "stderr").unwrap();
    writeln!(&mut stdout, "stdout").unwrap();
    writeln!(&mut stderr, "stderr").unwrap();
    writeln!(&mut stdout, "stdout").unwrap();
    println!("println");
    eprintln!("eprintln");
    
    stderr.reset().unwrap();  // FIXME: without this, prompt is colored green until user runs something like "ls"
}
    
// Output in a terminal where stdout and stderr are both written:
// stderr   # red, intended
// stdout   # green, intended
// stderr   # green, NOT intended
// stdout   # green, intended
// println  # green, not intended but understandable
// eprintln # green, NOT intended
```

The main problem is that the third line has green-colored "stderr" content.  The line with the "FIXME" label about resetting the colors isn't a bug, but it was surprising, and I think it would be nice to include it in the example code snippets in the documentation.

For the main problem, it'd be ideal if there was some way to track which stream was last written to, so color codes could be emitted as-necessary.  That would only write unnecessary bytes when someone was redirecting one of the streams.  Failing that, I think I'd be happy enough with a `write` macro that would sandwich my content between a color code and a reset code for each call.

I was observing this on xfce4-terminal 0.6.3 and a PuTTY connection from a Windows 10 box to a CentOS 6 machine, FWIW.

**Comment by BurntSushi** [comment]
Yeah, this is definitely intended behavior, and is just simply how colors work. It's not really a behavior prescribed by termcolor itself; all it does it pass through your color settings as ANSI escape sequences to the underlying stream. It is plausible that there may exist some other better ergonomic API, but it would almost certainly come with some form of cost, so I'd like to see that as a separate crate that perhaps uses `termcolor` as a dependency.

I would certainly be happy to have termcolor's documentation improved though. A short description or links to how coloring works would be good I think.

**Comment by romanows** [comment]
Sounds good.  If you can leave this open for a day or so, I'll see if I can think of a couple sentences that would have made it clear what's going on to someone like me.

**Comment by BurntSushi** [comment]
That would be great, thanks! And yeah, we can definitely keep this open.

**Comment by romanows** [comment]
I wasn't entirely sure how you're thinking about the module and the docs but here's a blurb that might spark something.  I was thinking it could go after the stdout example code:

> Note that any text written to the terminal now will be colored green, even if it is written via stderr, and even if stderr had previously been set to `Color::Red`.  Users will need to manage any color changes themselves by calling `WriteColor::set_color()`, and this may include calling `WriteColor::reset()` before the program exits to a shell.

We could also add a couple lines into the example code to make it clear what will happen and add the call to `reset` at the end.  Although maybe that's complicating the example code unnecessarily.
