### ISSUE TITLE
Avoid escapes when redirecting output?

### ISSUE THREAD

**Issue by andrewdavidmackenzie** [BurntSushi/termcolor#61]
I am using termcolor in my simple logging crate, to do colored output according to the log level of each line.
This works well interactively.

However, when I redirect output to a file, the file has the escape sequences, thus:

```
[0m[35mINFO	- Server is waiting to receive a 'Submission'
[0m[32mTRACE	- Server waiting for message from client
[0m[32mTRACE	-                 ---> Server Received ClientMessage ClientSubmission
[0m[34mDEBUG	- Server received a submission for execution with manifest_url: 'file:///Users/andrew/workspace/flow/flowsamples/prime'
```

which I see when editing the file later in an editor, or when using cat/more to display in the same terminal.

<img width="543" alt="Screen Shot 2022-04-26 at 10 40 38 AM" src="https://user-images.githubusercontent.com/5529132/165259445-30d4856b-43dd-4466-9d68-14335a805805.png">

I wondered if there is a way to have termcolor suppress colors when the terminal output is redirected?

If not, I will investigate doing it in my crate, but wanted to check if termcolor had already contemplated this before proceeding.

**Comment by andrewdavidmackenzie** [comment]
FYI investigating a bit:
https://stackoverflow.com/questions/54013753/is-there-a-cross-platform-way-to-check-if-stdout-is-being-piped-into-another-pro

**Comment by BurntSushi** [comment]
Yes, this is beyond the scope of `termcolor`. The `tty` check should be done by folks _using_ `termcolor`, and indeed, I would recommend the `atty` crate for that purpose.
