### ISSUE TITLE
Color codes written to file when stdout or stderr is redirected to file

### ISSUE THREAD

**Issue by romanows** [BurntSushi/termcolor#7]
When running on CentOS 6.9, redirecting stdout or stderr to a file causes color codes to still be written to a file when `ColorChoice` is set to `Always` or `Auto`.  Desired behavior is that color codes not be written when streams are redirected to a file.

The issue seems to be that on my system, the `TERM` environment variable is still `xterm` when the streams are redirected.  This causes termcolor to still [attempt to emit color codes](https://github.com/BurntSushi/termcolor/blob/3d81680656c9a4b82872504064ad77202f57e36e/src/lib.rs#L166).

Checking whether [stdout or stderr is a tty via a call to libc](https://rosettacode.org/wiki/Check_input_device_is_a_terminal#Rust) works, at least on Linux systems.  Based on that, I'm using something like:

```rust
extern crate libc;
let istty = unsafe { libc::isatty(libc::STDERR_FILENO as i32) } != 0;
let mut stderr = StandardStream::stderr(if istty {ColorChoice::Always} else {ColorChoice::Never});
```

Not sure if this is something you even want to tackle.  I'm filing the issue just in case anyone else comes along with a similar question.

**Comment by BurntSushi** [comment]
Yes, I've thought about whether `termcolor` should check the tty, but have thus far come down on the side of not doing it. Using `libc` directly is not the recommended way to do this. Instead, you should use the [`atty`](https://docs.rs/atty/0.2.11/atty/), which works on Windows as well.

This is at least worthy of better docs to point folks to `atty`.
