### ISSUE TITLE
Consider supporting FORCE_COLOR environmental variable

### ISSUE THREAD

**Issue by matklad** [BurntSushi/termcolor#71]
This is more of a braindump rather than a well-considered feature request, as I am not an expert in the domain. The TL;DR is that there's [`FORCE_COLOR`](https://petermekhaeil.com/til/add-color-using-force-color/) env variable, which is the opposite of `NO_COLOR`, and it might be nice to support it. 

Background: I am writing a thing which spawns other processes (like `cargo`) via `std::process::Command`. The thing is definitely _not_ a terminal emulator, so the subprocess stdout is normal pipe, rather than a TTY. My thing is also capable of parsing ANSI escapes, so it would very much like to receive colored output from subprocess. I wold love to have a general, cross-platform way to tell subprocesses "give me ANSI colors!" and I would love this not involving ioctl to the kernel (the way ttys work). The `FORCE_COLOR` feels like this solution. 

However, there's a problem: unlike `NO_COLOR`, `FORCE_COLOR` isn't a "real standard". I _think_ this is just a thing that `node` is doing. However, it seems like it at least becomes a de-facto standard. See, for example, the list of references in https://github.com/python/mypy/issues/13806 (but, of course, node and python interpret this value differently: `FORCE_COLOR=0` force-disables colors for node, and force-enables colors for Python).

**Comment by BurntSushi** [comment]
The problem is that there are multiple answers to this. For example, #41. And in practice, I'm not sure I really think the goal of "having one true way to force colors for applications" is probably just not going to happen unfortunately.

I resisted #41 because I don't really want to be in the business of just supporting a bunch of different random environment variables. I for example wonder whether it was right to add `NO_COLOR` support, but I'm not sure I want to expand on what I think might have been a mistake.

**Comment by matklad** [comment]
Yeah, it does seem that at this point this is just a "random environment variable". The momentum in the python ecosystem seems strong and recent though, so I wouldn't be surprised if this ends up a standard in the future, but it's wrong for `termcolor` to be a pioneer here. Probably best to close this issue (which is still valuable as a record of prior art!).

**Comment by matklad** [comment]
For posterity, good recent summary of the state of things in this area: https://github.com/hashicorp/terraform/issues/23708#issuecomment-1439325175

**Comment by BurntSushi** [comment]
> The momentum in the python ecosystem seems strong and recent though, so I wouldn't be surprised if this ends up a standard in the future

Yeah... I would have said that about `CLICOLOR` too. Hell, there is even a Rust crate for it: https://github.com/mitsuhiko/clicolors-control

And the terraform folks hit the same issue I had when considering whether to add more environment variables: how do they interact with one another? Which one wins?
