### ISSUE TITLE
Remove atty recommendation

### ISSUE THREAD

**Issue by daboross** [BurntSushi/termcolor#73]
It looks like `atty` has a reported possible unsoundness when using a custom global allocator, and hasn't updated to fix it: https://rustsec.org/advisories/RUSTSEC-2021-0145.html / https://github.com/softprops/atty/issues/50.

I think it could be reasonable to replace the `atty` recommendation in [the detecting-presence-of-a-terminal docs](https://docs.rs/termcolor/latest/termcolor/#detecting-presence-of-a-terminal) with an alternative, potentially [is-terminal](https://github.com/sunfishcode/is-terminal).

**Comment by BurntSushi** [comment]
Have you seen #70?
